language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.0
sudo: false
services:
  - redis-server
  - postgresql
  - cassandra
notifications:
  slack: dsp-s:rqHqJt1cm7hJXXqWTFvF7bdv
before_script:
  - psql -c 'create database dsps_travis_ci_test;' -U postgres
env:
  - MIX_ENV=travis
branches:
  only:
  - master
  - develop